version: "3"

services:
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"

  checker:
    image: vensder/ssl-cert-checker
    depends_on:
      - redis
    environment:
      - IS_FIRST_LOAD_FROM_FILE_ENABLED=True

  dashboard:
    image: vensder/ssl-checker-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - checker
    environment:
      - REDIS_HOST=redis
    command:
      [
        "--worker-tmp-dir /dev/shm",
        "--log-file=-",
        "--workers=2",
        "-b 0.0.0.0:8080",
      ]

