version: "3"

services:
  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"

  cron:
    build:
      context: ./cron
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - SECONDS_BETWEEN_INFO_UPDATES=7200
      - SECONDS_BETWEEN_CHECKS_FOR_OUTDATING=600
      - SECONDS_BETWEEN_FILE_CHECKS=30
      - IS_HASH_SUM_CHECK_ENABLED=False

  web-app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - cron
    environment:
      - REDIS_HOST=redis
      - TZ=Pacific/Auckland
      - SECONDS_BETWEEN_INFO_UPDATES=7200
      - SECONDS_BETWEEN_CHECKS_FOR_OUTDATING=600
      - SECONDS_BETWEEN_UPDATE_ABSENT=10
    command:
      [
        "--worker-tmp-dir /dev/shm",
        "--log-file=-",
        "--workers=2",
        "-b 0.0.0.0:8080",
      ]
    # command:
    #   [
    #     "--worker-tmp-dir /dev/shm",
    #     "--log-file=-",
    #     "--workers=2",
    #     "--threads=4",
    #     "--worker-class=gthread",
    #     "-b 0.0.0.0:8080",
    #   ]
